Use xmm0 to pass context to post_clone_hook
srg-imperial/SaBRe pull request #88
Opened 2022-07-24 11:57 UTC by RiscInside

This PR modifies `clone_syscall` and `clone3_syscall` signatures to accept context argument (one `void *`). This context argument can then be accessed from the post clone hook.

The implementation uses `xmm0` as a vehicle to pass the context argument to the child. The assumption is that it's unlikely libc `clone()` wrappers or other `clone()` users will depend on the value of `xmm0` in the child thread. `xmm0` value is set to NaN (ff bit pattern) after `post_clone_hook` exits, which should allow us to catch some instances of that not being the case.

Parent can use `xmm0` freely, as we save its value on `clone_syscall` /`clone3_syscall` function entry.

2022-07-24 12:06 UTC, RiscInside commented
CI fail was caused by me doing `+16(%rbp)` (as opposed to `16(%rbp`). This worked on my machine, but not on the CI. Fixed now

2022-07-25 11:02 UTC, andronat requested changes

2022-07-25 11:02 UTC, andronat commented on plugin_api/arch/x86_64/clone_syscall.s
> +  addq $16, %rsp
Change the above, to:
```
# Parent

# Restore xmm0
movdqu (%rsp), %xmm0
addq $16, %rsp
```

2022-07-25 11:02 UTC, andronat commented on plugin_api/recursion_protector.c
> +  (void)arg;
just add a comment after the `;` with `// unused`.

2022-07-25 11:03 UTC, andronat commented
Excellent! Fix those nits and we merge it asap 😎

2022-07-25 11:30 UTC, RiscInside commented
@andronat should be fixed now

2022-07-25 12:27 UTC, andronat approved these changes

2022-07-25 12:27 UTC, merged